# Generated by Django 4.1.7 on 2023-03-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_schools_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schools',
            options={'verbose_name_plural': '学校'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name_plural': '生徒'},
        ),
    ]
